#Vytvorenie kurierskej objednavky ako unlogin user
import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://twww.dpdmojkurier.sk/")
    page.get_by_role("button", name="Prijať všetko").click()
    page.get_by_role("link", name="Poslať zásielku").first.click()
    page.get_by_role("button", name="Pokračovať").nth(1).click()
    page.get_by_role("textbox", name="Meno").click()
    page.get_by_role("textbox", name="Meno").fill("Lucia")
    page.get_by_role("textbox", name="Priezvisko").click()
    page.get_by_role("textbox", name="Priezvisko").fill("Pie3ov8")
    page.get_by_role("textbox", name="Priezvisko").click()
    page.get_by_role("textbox", name="Priezvisko").fill("Piešová")
    page.get_by_role("textbox", name="Email").click()
    page.locator("div").filter(has_text=re.compile(r"^Email$")).nth(1).click()
    page.get_by_role("textbox", name="Email").fill("lucia.piesova")
    page.get_by_role("textbox", name="Email").press("Alt+ControlOrMeta+@")
    page.get_by_role("textbox", name="Email").fill("lucia.piesova+c1107")
    page.get_by_role("textbox", name="Email").press("Alt+ControlOrMeta+@")
    page.get_by_role("textbox", name="Email").fill("lucia.piesova+c11072")
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").dblclick()
    page.get_by_role("textbox", name="Email").click()
    page.get_by_role("textbox", name="Email").fill("lucia.piesova+c11072@bootiq.io")
    page.get_by_role("textbox", name="Telefón").click()
    page.get_by_role("textbox", name="Telefón").fill("+421918304547")
    page.locator("div").filter(has_text=re.compile(r"^MestoPSČ$")).get_by_role("textbox").nth(1).click()
    page.locator("div").filter(has_text=re.compile(r"^MestoPSČ$")).get_by_role("textbox").nth(1).fill("90021")
    page.locator("div").filter(has_text=re.compile(r"^MestoPSČSvätý Jur$")).get_by_role("textbox").first.click()
    page.locator("div").filter(has_text=re.compile(r"^MestoPSČ$")).get_by_role("textbox").first.fill("S")
    page.get_by_role("menuitem", name="Svätý Jur -").click()
    page.get_by_role("textbox", name="Ulica").click()
    page.get_by_role("textbox", name="Ulica").fill("1.maja")
    page.get_by_role("textbox", name="Popisné číslo").click()
    page.get_by_role("textbox", name="Popisné číslo").fill("22")
    page.get_by_role("checkbox", name="Prosím, pre ďalší krok a").check()
    page.get_by_role("button", name="Pokračovať").click()
    page.get_by_role("textbox", name="Meno").click()
    page.get_by_role("textbox", name="Meno").fill("Peter")
    page.locator("div").filter(has_text=re.compile(r"^Priezvisko$")).nth(1).click()
    page.get_by_role("textbox", name="Priezvisko").fill("Valigursky")
    page.get_by_role("textbox", name="Email").dblclick()
    page.get_by_role("textbox", name="Email").fill("lucia.piesova+c1107@bootiq.io")
    page.get_by_role("textbox", name="Telefón").click()
    page.get_by_role("textbox", name="Telefón").fill("+421918304547")
    page.locator("div").filter(has_text=re.compile(r"^MestoPSČ$")).get_by_role("textbox").nth(1).click()
    page.locator("div").filter(has_text=re.compile(r"^MestoPSČ$")).get_by_role("textbox").nth(1).fill("83102")
    page.get_by_text("Bratislava Nové Mesto").click()
    page.locator("div").filter(has_text=re.compile(r"^Ulica$")).nth(1).click()
    page.get_by_role("textbox", name="Ulica").fill("Vajnirska")
    page.get_by_role("textbox", name="Popisné číslo").dblclick()
    page.get_by_role("textbox", name="Popisné číslo").fill("2")
    page.get_by_role("button", name="Pokračovať").click()
    page.get_by_role("img", name="add-parcel-icon").click()
    page.locator("div").filter(has_text=re.compile(r"^váha:do 5 kgdĺžka:55 cmšírka:45 cmvýška:20 cmPridať$")).get_by_role("button").click()
    page.get_by_role("img", name="add-parcel-icon").click()
    page.locator("div").filter(has_text=re.compile(r"^váha:do 5 kgdĺžka:55 cmšírka:45 cmvýška:20 cmPridať$")).get_by_role("button").click()
    page.get_by_role("button", name="Pokračovať").click()
    page.get_by_role("button", name="Pokračovať na výber platby").click()
    page.get_by_role("radio", name="Platba pri vyzdvihnutí balíka").check()
    page.get_by_role("button", name="Potvrdiť objednávku").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
